### ISSUE TITLE
Multi-currency Interface

### ISSUE THREAD

**Issue by deckar01** [stellar/stellar-client#654]
Implement the multi-currency interface https://github.com/stellar/stellar-prototypes/tree/multicurrency-prototype.
- [ ] #657 Show multiple balances in dashboard
- [ ] #659 Show "all balances" pane in dashboard
- [ ] #662 Manage gateways
  - [ ] Search for gateways
  - [ ] Trust/remove gateway
- [ ] #664 Send currency
- [ ] #665 Send via currency
