### ISSUE TITLE
UI for trading interface

### ISSUE THREAD

**Issue by jedmccaleb** [stellar/stellar-client#760]
**Implement the UI for trading currencies**
- [x] #756 The trading interface will exist as an advanced feature that must be opted into in the settings.
- [x] #763 Turning on this feature displays a link in the header that navigates to trading page.
- [x] #764 Implement the basic trading form.
- [x] #812 Trading form notifications.
- [x] #819 Trade confirmation overlay.
- [x] #761 Implement favorite trades that are saved in the wallet.
- [x] #765 Implement modules for summarizing order books.

First draft is here: https://www.dropbox.com/sh/mdochhb2wqnwije/AABnOkUM0YMtOzEngkNQWiU7a
![screen shot 2014-09-03 at 2 45 58 pm](https://cloud.githubusercontent.com/assets/3108007/4142078/cc329e94-33b4-11e4-8b38-d806c81f0a77.png)
