### ISSUE TITLE
Trading client front-end/design checklist

### ISSUE THREAD

**Issue by wynlim** [stellar/stellar-client#844]
For design/front-end to keep track of:
- [x] overall styling pass
- [x] mobile styling pass
- [x] favorite pairs #761
- [x] bid/ask widget #765
- [x] corresponding balance widget #849
- [ ] check default ux states/data in place
- [ ] check entire trading ux flow
- [ ] check error states
- [ ] check tx history
- [x] total payable should be editable #854
